# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-20 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corex', '0003_auto_20201020_0306'),
    ]

    operations = [
        migrations.AddField(
            model_name='atc',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='atc',
            name='letter',
            field=models.CharField(max_length=1),
        ),
    ]
