# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-20 19:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corex', '0017_clinical_trials'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kernel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kernel_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Kernel_file_name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.TextField(max_length=200)),
                ('kernel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corex.Kernel')),
            ],
        ),
        migrations.CreateModel(
            name='Kernel_Protein_index',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('kernel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corex.Kernel')),
                ('protein', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corex.Protein')),
            ],
        ),
        migrations.AddField(
            model_name='protein_network',
            name='url',
            field=models.URLField(default='nourl', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kernel_file_name',
            name='protein_network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corex.Protein_network'),
        ),
        migrations.AddField(
            model_name='protein',
            name='kernels',
            field=models.ManyToManyField(through='corex.Kernel_Protein_index', to='corex.Kernel'),
        ),
        migrations.AddField(
            model_name='protein_network',
            name='kernel_files',
            field=models.ManyToManyField(through='corex.Kernel_file_name', to='corex.Kernel'),
        ),
    ]
