# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-20 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corex', '0019_auto_20201120_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kernel',
            name='kernel_name',
            field=models.CharField(max_length=25),
        ),
    ]
