# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-20 05:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ATC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter', models.CharField(max_length=1)),
                ('category', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_bank_id', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=50)),
                ('cmap_score', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.AddField(
            model_name='atc',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corex.Drug'),
        ),
    ]
