# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-20 05:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corex', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='cmap_score',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
