# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-20 06:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corex', '0002_auto_20201020_0252'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atc',
            old_name='artist',
            new_name='drug',
        ),
        migrations.RemoveField(
            model_name='atc',
            name='id',
        ),
        migrations.AlterField(
            model_name='atc',
            name='letter',
            field=models.CharField(max_length=1, primary_key=True, serialize=False),
        ),
    ]
