# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-21 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corex', '0008_auto_20201021_1406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drug',
            name='atcs',
        ),
        migrations.AddField(
            model_name='atc',
            name='drugs',
            field=models.ManyToManyField(to='corex.Drug'),
        ),
    ]
