# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-06 03:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corex', '0013_auto_20201023_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='cmap_score',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='interactions',
            name='weight',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='protein',
            name='host_protein',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='protein',
            name='name',
            field=models.TextField(max_length=100),
        ),
    ]
