# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-06 03:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corex', '0014_auto_20201106_0038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drug',
            name='atcs',
        ),
        migrations.RemoveField(
            model_name='drug',
            name='targets',
        ),
        migrations.RemoveField(
            model_name='interactions',
            name='p1',
        ),
        migrations.RemoveField(
            model_name='interactions',
            name='p2',
        ),
        migrations.RemoveField(
            model_name='interactions',
            name='protein_network',
        ),
        migrations.DeleteModel(
            name='ATC',
        ),
        migrations.DeleteModel(
            name='Drug',
        ),
        migrations.DeleteModel(
            name='Interactions',
        ),
        migrations.DeleteModel(
            name='Protein',
        ),
        migrations.DeleteModel(
            name='Protein_network',
        ),
    ]
