# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-17 06:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corex', '0016_auto_20201106_0047'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinical_Trials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ntc_number', models.CharField(max_length=15)),
                ('url', models.URLField(max_length=100)),
                ('title', models.TextField(max_length=100)),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corex.Drug')),
            ],
        ),
    ]
