# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-20 21:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corex', '0020_auto_20201120_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kernel_protein_index',
            name='kernel',
        ),
        migrations.RemoveField(
            model_name='protein',
            name='kernels',
        ),
        migrations.AddField(
            model_name='kernel_protein_index',
            name='network',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='corex.Protein_network'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='protein_network',
            name='kernel_index',
            field=models.ManyToManyField(through='corex.Kernel_Protein_index', to='corex.Protein'),
        ),
    ]
