# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-20 17:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corex', '0004_auto_20201020_1405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atc',
            name='drug',
        ),
        migrations.DeleteModel(
            name='ATC',
        ),
    ]
