# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-21 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corex', '0007_auto_20201020_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atc',
            name='drug',
        ),
        migrations.RemoveField(
            model_name='atc',
            name='id',
        ),
        migrations.AddField(
            model_name='drug',
            name='atcs',
            field=models.ManyToManyField(to='corex.ATC'),
        ),
        migrations.AlterField(
            model_name='atc',
            name='letter',
            field=models.CharField(max_length=1, primary_key=True, serialize=False),
        ),
    ]
