# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-21 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('corex', '0011_auto_20201021_1456'),
    ]

    operations = [
        migrations.CreateModel(
            name='ATC',
            fields=[
                ('letter', models.CharField(max_length=1, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_bank_id', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=50)),
                ('cmap_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('atcs', models.ManyToManyField(to='corex.ATC')),
            ],
        ),
    ]
