# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-12-28 22:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corex', '0021_auto_20201120_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='kernel_file_name',
            name='host_protein_indices_path',
            field=models.TextField(default='test', max_length=200),
            preserve_default=False,
        ),
    ]
