# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-18 21:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corex', '0022_kernel_file_name_host_protein_indices_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='kernel_protein_index',
            name='is_lcc',
            field=models.BooleanField(default=False),
        ),
    ]
